#!/usr/bin/env bash
# ==============================================================================
# Script Name : 02_Variables_Environment_IO_script.sh
# Description : Dynamic Application Config Generator & Environment Parser
# Day         : 02 - Variables, Memory Scoping, Environment Inheritance & Safe I/O
# ==============================================================================

set -euo pipefail
IFS=$'\n\t'

# ANSI Terminal Styling
readonly COLOR_RESET="\033[0m"
readonly COLOR_RED="\033[1;31m"
readonly COLOR_GREEN="\033[1;32m"
readonly COLOR_YELLOW="\033[1;33m"
readonly COLOR_BLUE="\033[1;34m"
readonly COLOR_CYAN="\033[1;36m"
readonly COLOR_BOLD="\033[1m"

# Standardized Logging Facade
log_info() {
    printf "${COLOR_BLUE}[INFO]${COLOR_RESET} %s\n" "$*"
}

log_success() {
    printf "${COLOR_GREEN}[SUCCESS]${COLOR_RESET} %s\n" "$*"
}

log_warn() {
    printf "${COLOR_YELLOW}[WARN]${COLOR_RESET} %s\n" "$*" >&2
}

log_error() {
    printf "${COLOR_RED}[ERROR]${COLOR_RESET} %s\n" "$*" >&2
}

# Trap handler for safe cleanup
cleanup() {
    local exit_code=$?
    if [ "${exit_code}" -ne 0 ]; then
        log_error "Configuration generation failed with status: ${exit_code}"
    fi
}
trap cleanup EXIT

# Function: Parse and display system environment variables
parse_environment_context() {
    log_info "Analyzing environment variables from symbol table and envp..."

    local current_user="${USER:-$(id -un 2>/dev/null || echo "app_user")}"
    local home_directory="${HOME:-/tmp}"
    local path_entries
    
    # Split PATH by colon safely without subshell fork
    IFS=':' read -r -a path_entries <<< "${PATH:-/usr/bin:/bin}"
    IFS=$'\n\t'

    printf "\n"
    printf "${COLOR_CYAN}%-22s :${COLOR_RESET} %s\n" "Current User" "${current_user}"
    printf "${COLOR_CYAN}%-22s :${COLOR_RESET} %s\n" "Home Directory" "${home_directory}"
    printf "${COLOR_CYAN}%-22s :${COLOR_RESET} %d entries\n" "PATH Binary Search Paths" "${#path_entries[@]}"
    printf "${COLOR_CYAN}%-22s :${COLOR_RESET} %s\n" "Primary Path Segment" "${path_entries[0]:-none}"
    printf "\n"
}

# Function: Prompt and safely capture user configuration inputs
prompt_configuration_inputs() {
    local default_app_name="CloudSentinel"
    local default_port="8080"
    local default_timeout_sec="15"

    log_info "Collecting deployment configuration parameters..."

    # Interactive or non-interactive detection
    if [ -t 0 ]; then
        # 1. Capture App Name with timeout
        printf "${COLOR_BOLD}Enter Application Name [default: %s] (timeout in %ss): ${COLOR_RESET}" "${default_app_name}" "${default_timeout_sec}"
        if read -r -t "${default_timeout_sec}" input_app_name; then
            CFG_APP_NAME="${input_app_name:-${default_app_name}}"
        else
            printf "\n"
            log_warn "Input timeout reached. Falling back to default app name."
            CFG_APP_NAME="${default_app_name}"
        fi

        # 2. Capture Port Number
        printf "${COLOR_BOLD}Enter Service Port [1-65535, default: %s]: ${COLOR_RESET}" "${default_port}"
        read -r input_port
        CFG_PORT="${input_port:-${default_port}}"

        # 3. Capture Secret Token with Silent Mode (-s)
        printf "${COLOR_BOLD}Enter Application Secret API Key (Input Hidden): ${COLOR_RESET}"
        read -r -s input_secret
        printf "\n"
        CFG_SECRET_KEY="${input_secret:-default_demo_secret_token_$(date +%s)}"
    else
        log_info "Non-interactive execution detected (e.g. pipeline). Applying defaults."
        CFG_APP_NAME="${default_app_name}"
        CFG_PORT="${default_port}"
        CFG_SECRET_KEY="automated_ci_cd_key_$(date +%s)"
    fi

    # Input Validation
    if ! [[ "${CFG_PORT}" =~ ^[0-9]+$ ]] || [ "${CFG_PORT}" -lt 1 ] || [ "${CFG_PORT}" -gt 65535 ]; then
        log_error "Validation Failed: Invalid port number '${CFG_PORT}'. Must be integer 1-65535."
        return 1
    fi

    log_success "Input parameters validated successfully."
}

# Function: Render configuration file to disk
render_config_file() {
    local output_path="${1:-./app_generated_config.env}"
    log_info "Generating environment configuration file at: ${output_path}"

    cat << EOF > "${output_path}"
# ========================================================
# AUTO-GENERATED CONFIGURATION - DO NOT EDIT MANUALLY
# Generated At: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Generated By: ${USER:-$(id -un 2>/dev/null || echo "unknown")}
# ========================================================
APP_NAME="${CFG_APP_NAME}"
APP_PORT=${CFG_PORT}
APP_SECRET_TOKEN="${CFG_SECRET_KEY}"
APP_DEPLOYMENT_TIMESTAMP=$(date +%s)
APP_BASE_DIR="${PWD}"
EOF

    chmod 600 "${output_path}"
    log_success "Configuration written with secure permissions (0600: read/write owner only)."

    printf "\n${COLOR_CYAN}--- Config Content Preview ---${COLOR_RESET}\n"
    sed 's/APP_SECRET_TOKEN=.*/APP_SECRET_TOKEN=****************/' "${output_path}"
    printf "${COLOR_CYAN}------------------------------${COLOR_RESET}\n\n"

    # Verify presence and clean test artifact
    if [ -f "${output_path}" ]; then
        rm -f "${output_path}"
        log_info "Temporary configuration artifact cleaned up."
    fi
}

main() {
    printf "\n=================================================================\n"
    printf "       10-DAYS-OF-BASH : DAY 02 CONFIG GENERATOR & SAFE I/O      \n"
    printf "=================================================================\n\n"

    parse_environment_context
    prompt_configuration_inputs
    render_config_file "./test_config_day02_$$.env"

    log_success "Day 02 dynamic configuration generator completed successfully."
    exit 0
}

main "$@"
